#!/bin/bash
# Get completions added by different files. Output in format:
#  <path> <commands>...

get_completions() {
	# source the file
	source "${1}"

	# print the completed commands
	while read -a args; do
		set -- "${args[@]}"

		[[ ${1} == complete ]] || continue
		shift

		while :; do
			# eat the options, reach the command!
			case "${1}" in
				-[oAGWFCXPS])
					shift;; # eat the argument :)
				-*)
					;;
				*)
					break;;
			esac
			shift
		done

		echo "${@}"
	done < <(complete -p)
}

main() {
	compdir=${1:-$(${PKG_CONFIG:-pkg-config} --variable=completionsdir bash-completion)}

	local f
	for f in "${compdir}"/*; do
		# skip the common code file
		# (in case we're run in /usr/share/bash-completion)
		[[ ${f##*/} == bash_completion ]] && continue

		local compls=( $(get_completions "${f}") )

		echo "${f} ${compls[*]}"
	done
}

# load the global helpers
source /usr/share/bash-completion/bash_completion

# clean up existing completions
complete -r

# start the main function
main "${@}"
